"""Added UserRole type

Revision ID: 17b6c4f9911b
Revises: ab4bc122c9ea
Create Date: 2023-09-22 10:47:56.639470

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b6c4f9911b'
down_revision: str | None = 'ab4bc122c9ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WORKER', 'ADMIN', 'SUPPORT', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('WORKER', 'ADMIN',
                  'SUPPORT', name='userrole', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    sa.Enum('WORKER', 'ADMIN', 'SUPPORT', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
