"""Make relations from clients to company

Revision ID: c3007748f421
Revises: e2afac45c549
Create Date: 2023-09-27 12:02:37.352564

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3007748f421'
down_revision: str | None = 'e2afac45c549'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('company_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'company_id')
    # ### end Alembic commands ###
