"""Added client table

Revision ID: d6a91a58b295
Revises: 
Create Date: 2023-09-19 11:02:31.834953

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6a91a58b295'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ci', sa.String(length=13), nullable=True),
                    sa.Column('names', sa.String(length=40), nullable=True),
                    sa.Column('lastnames', sa.String(length=40), nullable=True),
                    sa.Column('phone', sa.String(length=13), nullable=False),
                    sa.Column('last_state', sa.String(length=10), nullable=True),
                    sa.Column('saraguros_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
