"""Remove saraguros_id column from clients table

Revision ID: e2afac45c549
Revises: 17b6c4f9911b
Create Date: 2023-09-27 11:27:33.975636

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2afac45c549'
down_revision: str | None = '17b6c4f9911b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_column('clients', 'saraguros_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('saraguros_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'meta')
    # ### end Alembic commands ###
