name: Apply migrations to dev DB if migrations folder changed

on:
  push:
    branches:
      - development

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.verify.outputs.changed }}
    steps:
      - uses: actions/checkout@v3

      - name: Check changes in migrations folder
        id: verify
        run: |
          if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep migrations/) ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{needs.check_changes.outputs.changed_files}} == 'true'
    environment: developmet

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SARAGUROS_API_URL: ${{ vars.SARAGUROS_API_URL }}
      SARAGUROS_API_TOKEN: ${{ vars.SARAGUROS_API_TOKEN }}
      OCR_LAMBDA_URL: ${{ vars.OCR_LAMBDA_URL }}
      OPENAI_KEY: ${{ vars.OPENAI_KEY }}
      TWILIO_SID: ${{ vars.TWILIO_SID }}
      TWILIO_TOKEN: ${{ vars.TWILIO_TOKEN }}
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      X_API_KEY: ${{ vars.X_API_KEY }}
      TWILIO_SENDER: ${{ vars.TWILIO_SENDER }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11.5
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.11.5

      - name: Install all packages
        run: pipenv install --dev

      - name: Apply migrations to DB dev
        run: pipenv run migrate
