name: Deploy Migrations to Staging

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: developmet

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11.5
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.11.5

      - name: Install all packages
        run: pipenv install --dev

      - name: Apply migrations to DB dev
        run: pipenv run migrate
