name: Deploy Migrations to Staging

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11.5
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11.5
          architecture: x64

      - name: Setup Pipenv with Python 3.11.5
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: --python ${{env.Python_ROOT_DIR}}/python.exe

      - name: Print Python 3.11.5 path content
        run: ls ${{env.Python_ROOT_DIR}}

      - name: Install all packages
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev

      - name: Apply migrations to DB dev
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run migrate
